FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  python3-opencv

COPY requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt

COPY run_vision.py /app/run_vision.py

CMD ["python3", "/app/run_vision.py"]
