FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    python3-opencv

COPY requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt

COPY run_ui.py /app/run_ui.py

CMD ["streamlit", "run", "run_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
